services:
  server:
    image: docker-todo-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_DATABASE=postgres
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432 # expose for external host connections
    volumes:
      - ./server/sql/:/var/lib/postgresql/data
      - ./server/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql # ./server/init.sql will run first
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
